/**
 * Verse-text integrity. Offline, no network — it reads a snapshot committed at
 * src/data/canonical/quranArabicCanonical.json, regenerated by
 * `node scripts/refresh-quran-canonical.mjs`.
 *
 * Three checks, in order of how much they prove:
 *
 *   1. COVERAGE  every verse entry has a snapshot row. A new verse without a
 *      snapshot fails here rather than silently going unchecked — which is the
 *      failure mode that makes a green suite a lie.
 *   2. LOCK      arabicText is byte-identical to the snapshot. Catches ANY
 *      change to verse text, down to a single haraka, including edits made by
 *      a well-meaning script. This is the check that would have caught the
 *      diacritic drift documented in CLAUDE.md.
 *   3. TRUTH     the consonantal skeleton of arabicText equals the skeleton of
 *      quran.com's text for the same ayah range. Catches truncation, a dropped
 *      clause, and a wrong/misnumbered ayah — the faults CLAUDE.md keeps
 *      re-litigating — while staying blind to this Mushaf's extra tajwid marks.
 *
 * ---------------------------------------------------------------------------
 * WHAT THESE CHECKS DO **NOT** CATCH — read this before trusting a green run:
 *
 *   · The ENGLISH translation. Not checked at all, by design. This app
 *     deliberately smooths translator brackets and writes "Allah" for "Allāh";
 *     exactly 1 of 155 entries matches raw Sahih International, so an
 *     automated English check is 154 false alarms. Translation accuracy
 *     remains a human review job and CLAUDE.md's rules still bind.
 *   · Whether the verse is the RIGHT verse for its slot. A perfectly intact
 *     ayah can still be the wrong choice for a mood or journey day, or be a
 *     fiqh ruling quoted out of context. Check 3 proves the text matches the
 *     audioKey, not that the audioKey was a good idea.
 *   · Truncation at RENDER time. A `numberOfLines` clamp with no expand
 *     affordance clips the ayah on screen while this test passes — the data is
 *     intact, the display is not. Nothing here reads a component.
 *   · The transliteration field. Never compared to anything.
 *   · An entry with no `audioKey`, or no `arabicText`. Both are skipped
 *     entirely, so adding a verse without an audioKey removes it from all
 *     three checks rather than failing one. Check 1 cannot see it either.
 *   · Hadith Arabic. Different file, different sources, not covered here.
 *
 * The snapshot's `remote` field is quran.com's `text_uthmani`. It is NOT
 * treated as more correct than our own text — our edition is richer, and
 * rewriting ours to match would strip 111+ tajwid marks from the Qur'an. It is
 * used only as an independent witness to the letters.
 */

import { quranContent } from '../data/quranData';
import canonicalJson from '../data/canonical/quranArabicCanonical.json';
import { arabicSkeleton } from '../utils/arabicSkeleton';

type CanonicalRow = { id: string; audioKey: string; arabic: string; remote: string };
/**
 * Keyed by Content id, not audioKey. Several Content rows cite the same ayah
 * range and do not always carry byte-identical text, so an audioKey-keyed
 * snapshot could lock only one of them.
 */
const canonical = canonicalJson as unknown as Record<string, CanonicalRow>;

/**
 * Skeleton differences that are known, understood, and accepted, keyed by
 * Content id. A key here is NOT a licence — each entry has to say why, and
 * adding one is a content decision, not a way to quiet a red test.
 */
const ACCEPTED_SKELETON_DEVIATIONS: Record<string, string> = {
  quran_4_1:
    'arabicText and transliteration open with the Basmala; primaryText, ' +
    'englishTranslation and source ("Surah An-Nisa 4:1") do not. The Arabic ' +
    'is therefore longer than the translation rendered beneath it. Left as ' +
    'authored pending a content decision.',
};

const verseEntries = quranContent.filter(
  (entry): entry is typeof entry & { arabicText: string; audioKey: string } =>
    typeof entry.arabicText === 'string' &&
    entry.arabicText.length > 0 &&
    typeof entry.audioKey === 'string' &&
    entry.audioKey.length > 0,
);

describe('Quran verse text integrity', () => {
  it('has at least one verse to check (guards against a parse/export regression)', () => {
    expect(verseEntries.length).toBeGreaterThan(100);
  });

  it('every verse entry has a canonical snapshot row', () => {
    const missing = verseEntries
      .filter((e) => !canonical[e.id])
      .map((e) => `${e.id} (${e.audioKey})`);
    if (missing.length) {
      throw new Error(
        `${missing.length} verse(s) have no snapshot:\n  ${missing.join('\n  ')}\n\n` +
          'Run: node scripts/refresh-quran-canonical.mjs',
      );
    }
  });

  describe('LOCK — arabicText is byte-identical to the committed snapshot', () => {
    it.each(verseEntries.map((e) => [e.id, e.audioKey] as const))(
      '%s (%s)',
      (id, audioKey) => {
        const entry = verseEntries.find((e) => e.id === id)!;
        const row = canonical[id];
        expect(row).toBeDefined();
        if (entry.arabicText === row.arabic) return;
        throw new Error(
          `Verse text for ${id} (${audioKey}) changed since the snapshot.\n` +
            `  snapshot: ${row.arabic}\n` +
            `  current : ${entry.arabicText}\n\n` +
            'If the change is intentional and verified against a reliable source, ' +
            're-run: node scripts/refresh-quran-canonical.mjs',
        );
      },
    );
  });

  describe('TRUTH — arabicText is the ayah its audioKey names, complete', () => {
    it.each(verseEntries.map((e) => [e.id, e.audioKey] as const))(
      '%s (%s)',
      (id, audioKey) => {
        const entry = verseEntries.find((e) => e.id === id)!;
        const row = canonical[id];
        expect(row).toBeDefined();

        const ours = arabicSkeleton(entry.arabicText);
        const theirs = arabicSkeleton(row.remote);
        if (ours === theirs) return;

        const accepted = ACCEPTED_SKELETON_DEVIATIONS[id];
        if (accepted) {
          expect(typeof accepted).toBe('string');
          return;
        }

        let i = 0;
        while (i < ours.length && i < theirs.length && ours[i] === theirs[i]) i++;
        const window = (s: string) => s.slice(Math.max(0, i - 20), i + 30);
        throw new Error(
          `${id} (${audioKey}) does not match quran.com for that ayah range.\n` +
            `  lengths : ours ${ours.length} vs quran.com ${theirs.length}\n` +
            `  diverges at character ${i}\n` +
            `  ours    : …${window(ours)}…\n` +
            `  quran   : …${window(theirs)}…\n\n` +
            'A shorter "ours" usually means the ayah was truncated or a clause dropped. ' +
            'If this deviation is deliberate, document it in ACCEPTED_SKELETON_DEVIATIONS.',
        );
      },
    );
  });

  /**
   * Negative control. A checker that only ever prints "passed" is untested, and
   * a normalizer aggressive enough to pass everything is worse than no check at
   * all — CLAUDE.md documents two checks that shipped as silent no-ops exactly
   * this way, one of them using an Arabic strip class that matched the entire
   * alphabet. These cases run on every suite so the checks above cannot rot
   * into no-ops unnoticed.
   */
  describe('the checks above actually have teeth', () => {
    const sample = verseEntries.find((e) => canonical[e.id])!;
    const remote = canonical[sample.id].remote;

    it('LOCK detects a single changed character', () => {
      const tampered = sample.arabicText.replace(/َ/, ''); // drop one fatha
      expect(tampered).not.toBe(sample.arabicText);
      expect(tampered === canonical[sample.id].arabic).toBe(false);
    });

    it('TRUTH detects a truncated ayah', () => {
      const full = arabicSkeleton(sample.arabicText);
      const truncated = arabicSkeleton(sample.arabicText.slice(0, Math.floor(sample.arabicText.length * 0.6)));
      expect(truncated).not.toBe(full);
      expect(truncated.length).toBeLessThan(full.length);
    });

    it('TRUTH detects a wholly different ayah', () => {
      const other = verseEntries.find((e) => e.id !== sample.id && e.arabicText.length > 40)!;
      expect(arabicSkeleton(other.arabicText)).not.toBe(arabicSkeleton(remote));
    });

    it('but TRUTH is NOT fooled into failing by this Mushaf’s tajwid marks', () => {
      // Adding the edition's own marks must not change the skeleton, or the
      // check would flag all 140 edition differences as content faults.
      const withMarks = sample.arabicText.replace(/ا/, 'اۭ');
      expect(withMarks).not.toBe(sample.arabicText);
      expect(arabicSkeleton(withMarks)).toBe(arabicSkeleton(sample.arabicText));
    });

    it('and the skeleton is not degenerate (it keeps real letters)', () => {
      const skel = arabicSkeleton(sample.arabicText);
      expect(skel.length).toBeGreaterThan(10);
      expect(skel).toMatch(/[ء-ي]/);
    });
  });
});
